### ISSUE TITLE
Attitude control: rad/degree conversion

### ISSUE THREAD

**Issue by MarWaltz** [SvenGronauer/phoenix-drone-simulation#3]
Hi Sven,

Thanks for the work! Brief question: Is the following line in the Attitude controller a bug or do we divide on purpose by 18 instead of 180 [degree]?

https://github.com/SvenGronauer/phoenix-drone-simulation/blob/b43e8881f8a253b1984f97924d0fcd59311573c2/phoenix_drone_simulation/envs/control.py#L253

Best,
Martin

**Comment by SvenGronauer** [comment]
Hi Martin,

We did clip the target body angle by purpose. Similarly, we clipped the attitude rate since we noticed that the transfers failed when the action range was selected too high, e.g., an Attitude rate control with the range [−360, 360]deg/s did not work whereas the range [−60, 60]deg/s showed good results.

Best, 
Sven
